language: java
jdk:
- oraclejdk8
branches:
  except:
  - doc-br
notifications:
  email:
    recipients:
    - magzhan.karasayev@allpay.kz
    on_success: change
    on_failure: always
script: "mvn clean install"
